### ISSUE TITLE
Document the anti-spam rules

### ISSUE THREAD

**Issue by levino** [okfde/froide-food#12]
Relates to https://github.com/okfde/froide-food/issues/11

So I found out that one can send up to 5 requests in 5 minutes and up to 6 requests in 6 hours. What other anti-spam rules are there and where can I find them?

While we are at it: Who came up with these rules? What is the point of allowing one more request after the five requests in the first five minutes but then no more request for 5:55 hours. Makes no sense to me. Either the number of requests per 6 hours should be increased to say 20 or one should only be able to make 6 requests in 6 hours and complete remove the five minute constraint.

**Comment by stefanw** [comment]
> where can I find them?

The [request throttle configuration can be found in the fragdenstaat_de repo](https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/settings/base.py#L420-L425).

> Who came up with these rules?

Not sure why it's relevant, but I came up with these rules.

> What is the point?

Stop people who are too enthusiastic in the moment, allow them to cool down and make more requests the rest of the day or week.

Usually anti-spam rules are not documented in order to make it not too easy for actual spammers.
